"""
generated by ChatGPT,
needs refactoring
"""

import asyncio
import functools


def async_cache(maxsize=None):
    cache = asyncio.LifoQueue(maxsize)

    def decorator(func):
        @functools.wraps(func)
        async def wrapper(*args, **kwargs):
            key = (args, tuple(kwargs.items()))
            for result, result_key in cache._queue:
                if result_key == key:
                    if result.done():
                        return await result
                    else:
                        await asyncio.sleep(0)
                        return await wrapper(*args, **kwargs)
            result = asyncio.Future()
            cache.put_nowait((result, key))
            try:
                result.set_result(await func(*args, **kwargs))
            except Exception as exc:
                result.set_exception(exc)
            return await result

        return wrapper

    return decorator
